# Generated by Django 3.2.5 on 2021-07-23 10:55

import address.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0004_auto_20210723_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_channel', models.IntegerField(choices=[(1, 'Phone'), (2, 'Email'), (3, 'Whatsapp')])),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=2048, null=True)),
                ('website', models.URLField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', address.models.AddressField(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=128)),
                ('phone', models.CharField(max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', address.models.AddressField(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('comm_pref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmdb_core.communicationpreferences')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Farmer'), (2, 'Consultant')])),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_type', models.JSONField(null=True)),
                ('production_methods', models.JSONField(null=True)),
                ('main_products', models.JSONField(null=True)),
                ('soil', models.JSONField(null=True)),
                ('tillage', models.JSONField(null=True)),
                ('fertilization', models.JSONField(null=True)),
                ('irrigation', models.JSONField(null=True)),
                ('uses_icides', models.BooleanField(null=True)),
                ('receives_funding', models.BooleanField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farmdb_core.organization')),
            ],
            bases=('farmdb_core.organization',),
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_size_approx', models.IntegerField(null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('public_profile', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farmdb_core.organization')),
                ('survey_answers', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmdb_core.surveyanswers')),
            ],
            bases=('farmdb_core.organization',),
        ),
        migrations.CreateModel(
            name='PersonToRoleToOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmdb_core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmdb_core.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmdb_core.role')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=32)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmdb_core.farm')),
            ],
        ),
    ]
